# Generated by Django 3.1 on 2021-04-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20210411_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='choice',
            new_name='answer',
        ),
    ]
